version: "3"
services:
  server:
    build: .
    ports:
      - "8080:8080"
    environment: 
      - datasource.url=jdbc:postgresql://postgresql_db:5432/dbname
      - datasource.username=dbuser
      - datasource.password=dbpass
    depends_on:
      - postgresql_db
    
  postgresql_db: 
    image: 'postgres:13.1-alpine'
    environment: 
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
    ports: 
      - '5433:5432'